version: '3.8'
services:
  app:
    build: .
    container_name: 12_sonhos_server
    env_file:
      - ./.env 
    ports:
      - "8080:${PORT}"
    depends_on:
      - db
 

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    env_file:
      - ./.env

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: